language: node_js
node_js:
  - 10

install: npm install

jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run test
    - stage: build
      script:
        - npm run build:browser

cache:
  directories:
    - node_modules

notifications:
  email: false
